import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy | Pratipal",
  description: "Read Pratipal's Privacy Policy on how we collect, use, and protect your personal data.",
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-stone-50 py-16 px-4">
      <div className="max-w-3xl mx-auto">
        <div className="mb-10">
          <Link href="/" className="text-xs text-emerald-600 hover:text-emerald-800 transition">← Back to Home</Link>
          <h1 className="mt-4 text-4xl font-bold text-stone-800" style={{ fontFamily: "'Playfair Display', serif" }}>
            Privacy Policy
          </h1>
          <p className="mt-2 text-sm text-stone-500">Last updated: March 25, 2026</p>
          <p className="mt-3 text-sm text-stone-600">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>
        </div>

        <div className="space-y-8 text-stone-700 text-sm leading-relaxed">

          <section>
            <h2 className="text-xl font-semibold text-stone-800 mb-4" style={{ fontFamily: "'Playfair Display', serif" }}>Interpretation and Definitions</h2>
            <h3 className="text-base font-semibold text-stone-800 mb-2">Interpretation</h3>
            <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            <h3 className="text-base font-semibold text-stone-800 mt-4 mb-2">Definitions</h3>
            <p className="mb-3">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to <a href="https://www.pratipal.in/" className="text-emerald-700 underline">https://www.pratipal.in/</a>.</li>
              <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><strong>Country</strong> refers to: Maharashtra, India</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
              <li><strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual. We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.</li>
              <li><strong>Service</strong> refers to the Website.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
              <li><strong>Website</strong> refers to <a href="https://www.pratipal.in/" className="text-emerald-700 underline">https://www.pratipal.in/</a>.</li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-800 mb-3" style={{ fontFamily: "'Playfair Display', serif" }}>Collecting and Using Your Personal Data</h2>
            <h3 className="text-base font-semibold text-stone-800 mb-2">Types of Data Collected</h3>
            <h4 className="text-sm font-semibold text-stone-800 mb-2">Personal Data</h4>
            <p className="mb-2">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
            <ul className="list-disc pl-5 space-y-1 mb-4">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
            </ul>
            <h4 className="text-sm font-semibold text-stone-800 mb-2">Usage Data</h4>
            <p className="mb-3">Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-800 mb-3" style={{ fontFamily: "'Playfair Display', serif" }}>Tracking Technologies and Cookies</h2>
            <p className="mb-3">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
            <ul className="list-disc pl-5 space-y-2 mb-4">
              <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
              <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company to count users who have visited those pages or opened an email and for other related website statistics.</li>
            </ul>
            <p className="mb-3">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
            <p className="mb-4">Where required by law, we use non-essential cookies only with Your consent. You can withdraw or change Your consent at any time through Your browser/device settings.</p>
            <p className="mb-2">We use both Session and Persistent Cookies for the purposes set out below:</p>
            <ul className="list-disc pl-5 space-y-3">
              <li>
                <strong>Necessary / Essential Cookies</strong> (Session Cookies, administered by Us) — Essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts.
              </li>
              <li>
                <strong>Cookies Policy / Notice Acceptance Cookies</strong> (Persistent Cookies, administered by Us) — Identify if users have accepted the use of cookies on the Website.
              </li>
              <li>
                <strong>Functionality Cookies</strong> (Persistent Cookies, administered by Us) — Allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-800 mb-3" style={{ fontFamily: "'Playfair Display', serif" }}>Use of Your Personal Data</h2>
            <p className="mb-2">The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc pl-5 space-y-2 mb-4">
              <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
              <li>To manage Your Account and registration as a user of the Service.</li>
              <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
              <li>To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication regarding updates or informative communications related to the functionalities, products or contracted services.</li>
              <li>To provide You with news, special offers, and general information about other goods, services and events which We offer.</li>
              <li>To manage Your requests to Us.</li>
              <li>For business transfers: to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
              <li>For other purposes such as data analysis, identifying usage trends, and to evaluate and improve our Service, products, services, marketing and your experience.</li>
            </ul>
            <p className="mb-2">We may share Your Personal Data in the following situations:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>With Service Providers</strong> to monitor and analyze the use of our Service, to contact You.</li>
              <li><strong>For business transfers</strong> in connection with any merger, sale of Company assets, financing, or acquisition.</li>
              <li><strong>With Affiliates</strong>, in which case we will require those affiliates to honor this Privacy Policy.</li>
              <li><strong>With business partners</strong> to offer You certain products, services or promotions.</li>
              <li><strong>With Your consent</strong> for any other purpose.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-800 mb-3" style={{ fontFamily: "'Playfair Display', serif" }}>Retention of Your Personal Data</h2>
            <p className="mb-3">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We apply different retention periods to different categories of Personal Data:</p>
            <ul className="list-disc pl-5 space-y-2 mb-3">
              <li><strong>User Accounts:</strong> retained for the duration of your account relationship plus up to 24 months after account closure.</li>
              <li><strong>Support tickets and correspondence:</strong> up to 24 months from the date of ticket closure.</li>
              <li><strong>Website analytics data:</strong> up to 24 months from the date of collection.</li>
              <li><strong>Server logs:</strong> up to 24 months for security monitoring and troubleshooting purposes.</li>
            </ul>
            <p>When retention periods expire, We securely delete or anonymize Personal Data. Residual copies may remain in encrypted backups for a limited period consistent with our backup retention schedule.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-800 mb-3" style={{ fontFamily: "'Playfair Display', serif" }}>Transfer of Your Personal Data</h2>
            <p className="mb-3">Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.</p>
            <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-800 mb-3" style={{ fontFamily: "'Playfair Display', serif" }}>Delete Your Personal Data</h2>
            <p className="mb-3">You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend, or delete Your information at any time by signing in to Your Account and visiting the account settings section, or by contacting Us.</p>
            <p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-800 mb-3" style={{ fontFamily: "'Playfair Display', serif" }}>Disclosure of Your Personal Data</h2>
            <h3 className="text-base font-semibold text-stone-800 mb-2">Business Transactions</h3>
            <p className="mb-3">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
            <h3 className="text-base font-semibold text-stone-800 mb-2">Law enforcement</h3>
            <p className="mb-3">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>
            <h3 className="text-base font-semibold text-stone-800 mb-2">Other legal requirements</h3>
            <p className="mb-2">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
              <li>Protect the personal safety of Users of the Service or the public</li>
              <li>Protect against legal liability</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-800 mb-3" style={{ fontFamily: "'Playfair Display', serif" }}>Security of Your Personal Data</h2>
            <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-800 mb-3" style={{ fontFamily: "'Playfair Display', serif" }}>Children's Privacy</h2>
            <p className="mb-3">Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.</p>
            <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-800 mb-3" style={{ fontFamily: "'Playfair Display', serif" }}>Links to Other Websites</h2>
            <p className="mb-3">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
            <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-800 mb-3" style={{ fontFamily: "'Playfair Display', serif" }}>Changes to this Privacy Policy</h2>
            <p className="mb-3">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
            <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-stone-800 mb-3" style={{ fontFamily: "'Playfair Display', serif" }}>Contact Us</h2>
            <p className="mb-2">If you have any questions about this Privacy Policy, You can contact us:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>By email: <a href="mailto:connect@pratipal.in" className="text-emerald-700 underline">connect@pratipal.in</a></li>
              <li>By visiting this page on our website: <a href="https://www.pratipal.in/" className="text-emerald-700 underline">https://www.pratipal.in/</a></li>
            </ul>
          </section>

        </div>
      </div>
    </div>
  );
}
