// Shared visual design system for every transactional email Pratipal sends.
// Build new emails with renderEmailLayout()/emailInfoCard()/emailButton()
// instead of hand-rolled markup, so every email — order, auth, invitation,
// booking — shares one identical shell, logo placement, and color language.
//
// Three hard rules, all learned from real broken test sends:
// 1. No emoji anywhere (subjects or body) — colorful pictographs are a known
//    spam-filter signal and render inconsistently across clients. Icons below
//    are plain monochrome glyphs instead.
// 2. No CSS flexbox/grid. Gmail's mobile apps strip `display:flex` entirely,
//    collapsing rows into unspaced inline text. Every layout here is built
//    with <table>/<td valign="middle"> — the actual cross-client-safe way to
//    align and space content in HTML email.
// 3. No inline <svg>. Gmail (web + mobile) strips inline SVG from the message
//    body outright. Icons are pre-rendered PNGs hosted at
//    pratipal.in/assets/email-icons/<color>/<name>.png (generated by
//    scripts/generate-email-icons.ts) and referenced via plain <img>, same as
//    the logo already is.

export const BRAND = {
  logoUrl: "https://pratipal.in/assets/footer_logo.png",
  name: "Pratipal",
  navy: "#232d5f",
  cta: "#d97745",
  bg: "#f4f5f2",
  cardBorder: "#eae7e0",
  rowBorder: "#f1efe9",
  infoCardBg: "#faf9f6",
  textMuted: "#6b7280",
  textDark: "#1f2430",
  success: "#15803d",
  successBg: "#f0fdf4",
  danger: "#b91c1c",
  dangerBg: "#fef2f2",
  warning: "#b45309",
  warningBg: "#fffbeb",
} as const;

// ─── Icons ──────────────────────────────────────────────────────────────────
// Minimal line-style icon set (24x24 viewBox, stroke-based). Add new keys here
// rather than reaching for an emoji character in a template.

const ICON_PATHS: Record<string, string> = {
  check: '<polyline points="4 12 10 18 20 6" />',
  x: '<line x1="6" y1="6" x2="18" y2="18" /><line x1="18" y1="6" x2="6" y2="18" />',
  lock: '<rect x="5" y="11" width="14" height="9" rx="2" /><path d="M8 11V7a4 4 0 0 1 8 0v4" />',
  mail: '<rect x="3" y="5" width="18" height="14" rx="2" /><polyline points="3 7 12 13 21 7" />',
  phone: '<path d="M6 3h4l2 5-3 2a12 12 0 0 0 6 6l2-3 5 2v4a2 2 0 0 1-2 2A17 17 0 0 1 4 5a2 2 0 0 1 2-2z" />',
  mapPin: '<path d="M12 21s-7-6.5-7-11a7 7 0 0 1 14 0c0 4.5-7 11-7 11z" /><circle cx="12" cy="10" r="2.3" />',
  card: '<rect x="3" y="6" width="18" height="13" rx="2" /><line x1="3" y1="10" x2="21" y2="10" />',
  tag: '<path d="M20 12.5 12.5 20 4 11.5V4h7.5z" /><circle cx="8" cy="8" r="1.2" fill="currentColor" stroke="none" />',
  calendar: '<rect x="4" y="5" width="16" height="16" rx="2" /><line x1="4" y1="9" x2="20" y2="9" /><line x1="8" y1="3" x2="8" y2="7" /><line x1="16" y1="3" x2="16" y2="7" />',
  clock: '<circle cx="12" cy="12" r="9" /><polyline points="12 7 12 12 16 14" />',
  link: '<path d="M9.5 14.5 14.5 9.5" /><path d="M12.5 5.5 14 4a3.6 3.6 0 0 1 5 5l-1.5 1.5" /><path d="M11.5 18.5 10 20a3.6 3.6 0 0 1-5-5l1.5-1.5" />',
  user: '<circle cx="12" cy="8" r="3.6" /><path d="M4.5 20.5c0-3.6 3.4-6 7.5-6s7.5 2.4 7.5 6" />',
  bag: '<path d="M6 8h12l1 12H5z" /><path d="M9 8V6a3 3 0 0 1 6 0v2" />',
  truck: '<rect x="2" y="7" width="12" height="9" rx="1" /><path d="M14 10h4l3 3v3h-7z" /><circle cx="7" cy="18" r="1.6" /><circle cx="17" cy="18" r="1.6" />',
  bell: '<path d="M6 10a6 6 0 0 1 12 0c0 5 2 6 2 6H4s2-1 2-6z" /><path d="M10 20a2 2 0 0 0 4 0" />',
  package: '<path d="M21 8l-9-5-9 5 9 5 9-5z" /><path d="M3 8v8l9 5 9-5V8" /><line x1="12" y1="13" x2="12" y2="21" />',
  refresh: '<path d="M21 12a9 9 0 1 1-3-6.7" /><polyline points="21 3 21 9 15 9" />',
  alertTriangle: '<path d="M12 3 22 20H2z" /><line x1="12" y1="9" x2="12" y2="14" /><circle cx="12" cy="17.3" r="0.9" fill="currentColor" stroke="none" />',
  messageCircle: '<path d="M21 11.5a8.4 8.4 0 0 1-8.4 8.4c-1.3 0-2.6-.3-3.7-.9L3 20l1-5.8a8.3 8.3 0 0 1-.9-3.7A8.4 8.4 0 0 1 11.5 3.1 8.4 8.4 0 0 1 21 11.5z" />',
  fileText: '<path d="M6 3h9l3 3v15H6z" /><line x1="9" y1="9" x2="15" y2="9" /><line x1="9" y1="13" x2="15" y2="13" /><line x1="9" y1="17" x2="13" y2="17" />',
  leaf: '<path d="M5 21c9 0 14-5 14-14 0-1 0-2-.1-3-9 0-14 5-14 14 0 1 0 2 .1 3z" /><path d="M5 21c4-6 8-9 14-11" />',
  ticket: '<path d="M4 8a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v2a2 2 0 0 0 0 4v2a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2v-2a2 2 0 0 0 0-4z" /><line x1="12" y1="7" x2="12" y2="17" stroke-dasharray="2 2" />',
};

export type IconName = keyof typeof ICON_PATHS;

const ICON_COLORS = {
  white: "#ffffff",
  gray: "#6b7280",
  dark: "#1f2430",
  success: "#15803d",
  danger: "#b91c1c",
  warning: "#b45309",
} as const;

export type IconColor = keyof typeof ICON_COLORS;

export const ALL_ICON_NAMES = Object.keys(ICON_PATHS) as IconName[];
export const ALL_ICON_COLORS = Object.keys(ICON_COLORS) as IconColor[];

const EMAIL_ICON_BASE_URL = "https://pratipal.in/assets/email-icons";

/**
 * Raw inline SVG markup for one icon+color combo — used ONLY by
 * scripts/generate-email-icons.ts to rasterize the PNG files served in
 * actual emails. Never reference this directly from a template; use
 * emailIcon() below, which emits an <img> tag instead.
 */
export function buildIconSvgMarkup(name: IconName, color: IconColor, size = 96): string {
  const path = ICON_PATHS[name] || ICON_PATHS.check;
  const hex = ICON_COLORS[color];
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="${hex}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${path}</svg>`;
}

export function emailIcon(name: IconName, opts?: { size?: number; color?: IconColor }): string {
  const { size = 20, color = "gray" } = opts || {};
  return `<img src="${EMAIL_ICON_BASE_URL}/${color}/${name}.png" width="${size}" height="${size}" alt="" style="display:block;border:0;outline:none;" />`;
}

// ─── Layout primitives (table-based — no flex/grid) ────────────────────────

export interface EmailLayoutOptions {
  /** Hidden preview text shown next to the subject in inbox lists. */
  preheader?: string;
  badgeIcon: IconName;
  heading: string;
  subheading?: string;
  bodyHtml: string;
  cta?: { label: string; url: string; icon?: IconName };
  /** Overrides the default "Questions? Reach us at..." footer line. */
  footerNote?: string;
}

export function renderEmailLayout(opts: EmailLayoutOptions): string {
  const { preheader, badgeIcon, heading, subheading, bodyHtml, cta, footerNote } = opts;

  return `
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:${BRAND.bg};">
<tr><td align="center" style="padding:28px 16px;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
${preheader ? `<div style="display:none;max-height:0;overflow:hidden;opacity:0;">${preheader}</div>` : ""}
<table role="presentation" width="560" cellpadding="0" cellspacing="0" border="0" style="max-width:560px;width:100%;">

  <tr><td style="padding:0 4px 20px;">
    <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr>
      <td valign="middle" style="padding-right:10px;"><img src="${BRAND.logoUrl}" width="32" height="32" alt="${BRAND.name}" style="display:block;border-radius:8px;" /></td>
      <td valign="middle" style="font-size:16px;font-weight:700;color:${BRAND.navy};letter-spacing:-0.01em;">${BRAND.name}</td>
    </tr></table>
  </td></tr>

  <tr><td style="background:#ffffff;border-radius:16px;border:1px solid ${BRAND.cardBorder};padding:36px 32px;">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0">
      <tr><td align="center" style="padding-bottom:22px;">
        <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr>
          <td width="52" height="52" align="center" valign="middle" style="background:${BRAND.navy};border-radius:50%;">${emailIcon(badgeIcon, { size: 24, color: "white" })}</td>
        </tr></table>
      </td></tr>
      <tr><td align="center" style="font-size:21px;line-height:1.3;color:${BRAND.textDark};font-weight:700;padding-bottom:8px;">${heading}</td></tr>
      ${subheading
        ? `<tr><td align="center" style="font-size:14px;color:${BRAND.textMuted};line-height:1.6;padding-bottom:26px;">${subheading}</td></tr>`
        : `<tr><td style="padding-bottom:22px;"></td></tr>`}
      <tr><td>${bodyHtml}</td></tr>
      ${cta
        ? `<tr><td align="center" style="padding-top:28px;">${emailButton(cta.label, cta.url, BRAND.cta, cta.icon)}</td></tr>`
        : ""}
    </table>
  </td></tr>

  <tr><td align="center" style="padding:20px 8px 0;">
    <p style="margin:0;font-size:12px;color:#9ca3af;">${footerNote ?? `Questions? Reach us at <a href="mailto:connect@pratipal.in" style="color:${BRAND.navy};">connect@pratipal.in</a>`}</p>
    <p style="margin:6px 0 0;font-size:11px;color:#b0b4bd;">© ${new Date().getFullYear()} Pratipal. All rights reserved.</p>
  </td></tr>

</table>
</td></tr>
</table>`;
}

export function emailInfoCard(rows: Array<{ icon: IconName; label: string; value: string }>): string {
  const rowsHtml = rows
    .map(
      (r, i) => `
  <tr><td style="padding:11px 16px;${i < rows.length - 1 ? `border-bottom:1px solid ${BRAND.rowBorder};` : ""}">
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr>
      <td valign="middle">
        <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr>
          <td valign="middle" style="padding-right:8px;">${emailIcon(r.icon, { size: 15, color: "gray" })}</td>
          <td valign="middle" style="font-size:13px;color:${BRAND.textMuted};white-space:nowrap;">${r.label}</td>
        </tr></table>
      </td>
      <td align="right" valign="middle" style="font-size:13px;font-weight:600;color:${BRAND.textDark};padding-left:12px;">${r.value}</td>
    </tr></table>
  </td></tr>`
    )
    .join("");
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:${BRAND.infoCardBg};border-radius:12px;margin-bottom:22px;">${rowsHtml}</table>`;
}

export function emailNote(html: string, tone: "success" | "danger" | "warning" | "neutral" = "neutral", icon?: IconName): string {
  const palette = {
    success: { bg: BRAND.successBg, color: BRAND.success, iconColor: "success" as IconColor },
    danger: { bg: BRAND.dangerBg, color: BRAND.danger, iconColor: "danger" as IconColor },
    warning: { bg: BRAND.warningBg, color: BRAND.warning, iconColor: "warning" as IconColor },
    neutral: { bg: BRAND.infoCardBg, color: BRAND.textDark, iconColor: "dark" as IconColor },
  }[tone];
  const iconCell = icon
    ? `<td valign="top" style="padding-right:10px;padding-top:1px;">${emailIcon(icon, { size: 15, color: palette.iconColor })}</td>`
    : "";
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:${palette.bg};border-radius:10px;margin-bottom:20px;"><tr><td style="padding:13px 16px;">
    <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr>${iconCell}<td style="font-size:13px;color:${palette.color};line-height:1.6;">${html}</td></tr></table>
  </td></tr></table>`;
}

export function emailStatusPill(label: string, tone: "success" | "danger" | "warning" | "neutral" = "neutral"): string {
  const palette = {
    success: { bg: BRAND.successBg, color: BRAND.success },
    danger: { bg: BRAND.dangerBg, color: BRAND.danger },
    warning: { bg: BRAND.warningBg, color: BRAND.warning },
    neutral: { bg: BRAND.infoCardBg, color: BRAND.textDark },
  }[tone];
  return `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="display:inline-table;"><tr><td style="background:${palette.bg};color:${palette.color};font-size:12px;font-weight:600;padding:5px 14px;border-radius:999px;">${label}</td></tr></table>`;
}

export function emailCodeBox(code: string): string {
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:${BRAND.infoCardBg};border:2px dashed ${BRAND.cardBorder};border-radius:12px;margin-bottom:22px;"><tr><td align="center" style="padding:20px;">
    <span style="font-size:34px;font-weight:800;letter-spacing:10px;color:${BRAND.navy};">${code}</span>
  </td></tr></table>`;
}

export function emailButton(label: string, url: string, color: string = BRAND.cta, icon?: IconName): string {
  const iconCell = icon
    ? `<td valign="middle" style="padding-right:8px;">${emailIcon(icon, { size: 15, color: "white" })}</td>`
    : "";
  return `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="display:inline-table;"><tr><td style="background:${color};border-radius:10px;">
    <a href="${url}" style="display:block;text-decoration:none;padding:13px 32px;">
      <table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr>${iconCell}<td valign="middle" style="color:#ffffff;font-size:14px;font-weight:600;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">${label}</td></tr></table>
    </a>
  </td></tr></table>`;
}
